name: expert_academy
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Google fonts
  google_fonts: ^3.0.1

  # Google Signin
  google_sign_in: ^5.4.2
  firebase_auth: ^3.11.1
  firebase_core: ^1.24.0

  # Cloud firestore
  cloud_firestore: ^3.5.1

  # Icons
  font_awesome_flutter: ^10.2.1
  cupertino_icons: ^1.0.2

  # State mangment
  provider: ^6.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  rename: ^2.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpe
